services:
  sevensix:
    container_name: sevensix_app
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

  postgres:
    image: postgres:15
    container_name: sevensix_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"       # Host port 5433 mapped to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: