"""modify user_uid field nullable true in Conversation

Revision ID: ee25c746a0c4
Revises: 3949afc463af
Create Date: 2025-05-21 17:23:31.049677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee25c746a0c4'
down_revision: Union[str, None] = '3949afc463af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'user_uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('conversations_user_uid_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_uid'], ['uid'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_user_uid_fkey', 'conversations', 'users', ['user_uid'], ['uid'])
    op.alter_column('conversations', 'user_uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
